# Generated by Django 3.1 on 2020-10-16 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_add_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_request',
            name='project_name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add_request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_requests', to='final.project'),
        ),
    ]
