# Generated by Django 3.1 on 2020-10-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20201016_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_file', models.FileField(upload_to='')),
            ],
        ),
    ]
