# Generated by Django 3.1 on 2020-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0007_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='project',
        ),
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ManyToManyField(to='final.Project'),
        ),
    ]
