# Generated by Django 3.1 on 2020-11-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_auto_20201101_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='project',
            new_name='projects',
        ),
    ]
