# Generated by Django 3.1 on 2020-11-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_auto_20201101_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='boards',
        ),
        migrations.AddField(
            model_name='board',
            name='projects',
            field=models.ManyToManyField(to='final.Project'),
        ),
    ]
