# Generated by Django 3.1 on 2020-11-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0011_auto_20201101_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='projects',
            field=models.ManyToManyField(blank=True, to='final.Project'),
        ),
    ]
