# Generated by Django 3.1 on 2020-11-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0012_auto_20201101_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(default='purple', max_length=64),
            preserve_default=False,
        ),
    ]
